In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('athlete_events.csv')
region_df=pd.read_csv('noc_regions.csv')

In [4]:
df.shape

(271116, 15)

In [5]:
df=df[df['Season']=='Summer']

In [6]:
df=df.merge(region_df,on='NOC',how='left')

In [7]:
df.drop_duplicates(inplace=True)

In [8]:
pd.get_dummies(df['Medal'])

        Bronze   Gold  Silver
0        False  False   False
1        False  False   False
2        False  False   False
3        False   True   False
4        False  False   False
...        ...    ...     ...
222547   False  False   False
222548   False  False   False
222549   False  False   False
222550   False  False   False
222551   False  False   False

[221167 rows x 3 columns]

In [9]:
df = pd.concat([df, pd.get_dummies(df['Medal'])], axis=1)

In [20]:
df.groupby('region').sum()[['Gold','Silver','Bronze']].sort_values('Gold',ascending=False).reset_index()

                      region  Gold  Silver  Bronze
0                        USA  2472    1333    1197
1                     Russia  1220     974     994
2                    Germany  1075     987    1064
3                         UK   635     729     620
4                      Italy   518     474     454
..                       ...   ...     ...     ...
200                  Vanuatu     0       0       0
201  Virgin Islands, British     0       0       0
202       Virgin Islands, US     0       1       0
203                    Yemen     0       0       0
204                   Zambia     0       1       1

[205 rows x 4 columns]

In [22]:
medal_tally=df.drop_duplicates(subset=['Team','NOC','Games','Year','City','Sport','Event','Medal'])

In [23]:
medal_tally=medal_tally.groupby('region').sum()[['Gold','Silver','Bronze']].sort_values('Gold',ascending=False).reset_index()

In [24]:
medal_tally

                      region  Gold  Silver  Bronze
0                        USA  1035     802     708
1                     Russia   592     498     487
2                    Germany   444     457     491
3                         UK   278     317     300
4                     France   234     256     287
..                       ...   ...     ...     ...
200                  Vanuatu     0       0       0
201  Virgin Islands, British     0       0       0
202       Virgin Islands, US     0       1       0
203                    Yemen     0       0       0
204                   Zambia     0       1       1

[205 rows x 4 columns]

In [25]:
medal_tally['total']=medal_tally['Gold']+medal_tally['Silver']+medal_tally['Bronze']

In [34]:
nations_over_time = df.drop_duplicates(['Year', 'region'])['Year'].value_counts().reset_index()

In [37]:
nations_over_time

    Edition  no of countries
0      2016              204
1      2012              203
2      2008              202
3      2004              200
4      2000              199
5      1996              196
6      1992              168
7      1988              156
8      1984              139
9      1972              120
10     1968              111
11     1964               93
12     1976               91
13     1960               83
14     1980               80
15     1956               71
16     1952               67
17     1948               59
18     1936               49
19     1932               47
20     1928               46
21     1924               45
22     1900               31
23     1912               29
24     1920               29
25     1908               22
26     1906               20
27     1904               14
28     1896               12

In [41]:
import plotly.express as px
fig = px.line(nations_over_time, x="Edition", y="no of countries")
nations_over_time.sort_values('Edition', inplace=True, ascending=True)
fig.show()

In [47]:
temp_df = df.dropna(subset=['Medal'])
x = temp_df['Name'].value_counts().reset_index().head(15).merge(df, left_on='ID', right_on='Name', how='left')[['ID', 'Name_x', 'Sport', 'region']].drop_duplicates('index')
# x.rename(columns={'index': 'Name', 'Name_x': 'Medals'}, inplace=True)
temp_df

KeyError: 'ID'

In [36]:
nations_over_time.rename(columns={'Year': 'Edition', 'count': 'no of countries'}, inplace=True)